### ISSUE TITLE
IIB Docker for Production Use

### ISSUE THREAD

**Issue by CodyKurtz** [ot4i/iib-docker#13]
Hi 

According to this link: https://developer.ibm.com/integration/blog/2015/12/02/ibm-integration-bus-now-supports-docker-for-production-use/ 

Docker and IIB are now supported for production use. I cannot find a production docker image. Would it be as simple as swapping out the install file? 

It would also be nice to see a Docker Compose file, that runs both a IIB and MQ docker container. 

Thanks

**Comment by s-rogers** [comment]
Hi - yes, if you have a licensed copy of IIB, then modifying the dockerfile by swapping out the HTTP download and unzip for a local install of your own binaries is certainly one way of creating a production ready image.  Providing a dockerfile with the IIB product is something we are investigating.  If you want to add in MQ to your image, then I would suggest looking at https://github.com/ibm-messaging/mq-docker.  You could extend that with the examples provided here and end up with a combined image.  Hope that helps.
