### ISSUE TITLE
installation failed

### ISSUE THREAD

**Issue by jwende** [ot4i/iib-docker#2]
I had to change the tar command from 'zx' to 'zxv' to enable the download and the extraction of the IIB archive file.
J.

**Comment by s-rogers** [comment]
This seems a strange one -  the "-v" flag just adds verbose output, so not sure why this would affect anything.  Can you provide more information on what errors you were seeing?

**Comment by jwende** [comment]
my mistake - it was related to a wrong filename in the 'curl' command
thanks
