### ISSUE TITLE
Build on windows 7 with VirtualBox

### ISSUE THREAD

**Issue by aerlank** [ot4i/iib-docker#23]
To get an image build I had to make a few changes to the Dockerfile. It might be ignorance on my side but I thought I would share anyway as it might be helpful.
Dockerfile:
1. downloading the 1.2GB install using curl did not work for me. Instead I included the *.tar.gz in the build files. As a result my container file size is 3.3GB :(
2. the --exclude options for the tar gave errors and I had to  remove that
3. /etc/sudoers does not exist

iib_manage.sh:
1. sudo does not exist

Everything works 100% now. Thank you for sharing and getting me started.
Amanda

**Comment by dennisseidel** [comment]
@aerlank Don't add the binary files directly with an ADD or COPY, there are at least two better option. 
1. Create a data volume and mount it into your container: https://docs.docker.com/engine/tutorials/dockervolumes/
2. Create a nginx container that includes the binaries and exposes them under a docker-host url: that should be more stable. 

I currently use both approaches, option 1 for the installation binaries and option two for keystores and stage specific overwrite files for our BAR Files. I hope that helps, there will be even more option I did not think about :-)

**Comment by aerlank** [comment]
Hi,
Please can you give me an example of what the build file will look like for: Create a data volume and mount it into your container

Amanda

**Comment by dennisseidel** [comment]
Hi Amanda,

Disclamer: I don't advertise using volume to mount binaries, as images should be immutable after build (except for stage/environment specific configurations), everything else make the container management complex and will not workout in the long run give you run a container platform with thousands of containers. I try to work on a better approach you can find it here: https://github.com/dennisseidel/iib-bestpractice-applications-template

Further the approach with containers will run under docker and docker-compose but not on kubernetes/openshift, again a reason why I will not advertise this any longer.  

But anyway, to use volumes you need to do 3 things : 
- create a image that only provides a mount with the binaries e.g. : 
  `FROM debian:latest
  RUN mkdir /iibBinary
  #the folder binary/ incudes the iib binaries
  ADD binary/* /iibBinary/
  VOLUME ["/iibBinary"]`
- mount the volume in your iib-dockerfile e.g. add the following line: 
  `VOLUME ["/iibBinary/"]`
- add the copying of the files to the entrypoint script (here iib-manage.sh) 
  `sudo cp -r /iibBinary/* /opt/ibm`
- at runtime use either the volume command of docker or user docker-compose to orchestrate the containers e.g. : 
  `version: '2'
  services:
  iib:
    image: iib:${IIB_VERSION}
    ports:
  - "4414"
  - "7800"
    volumes_from:
  - iib-binary
    iib-binary:
    container_name: "iib-binary"
    image: iib-binary:${IIB_VERSION}
    entrypoint: /bin/bash
    volumes:
  - iib-binary-10004:/iibBinary
    volumes:
    iib-binary-10004: {}`

**Comment by raghavendrarao79** [comment]
Hi Dennis,

  We have a docker image of IIB deployed on IBM Bluemix PaaS.
  We get a CORS problem when accessing a service on HTTP, from a client app on Bluemix:

   XMLHttpRequest cannot load http://x.x.x.x:7800/interface/chat. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://myapp.mybluemix.net' is therefore not allowed access.

  We did enable CORS on IIB server end - https://developer.ibm.com/integration/blog/2015/06/05/cross-origin-resource-sharing-cors-in-ibm-integration-bus-v10/, however, the issue persists...our IIB container instance version is 10.0.0.1.

  Any clues or ideas will serve useful...

Thanks in advance...

**Comment by dennisseidel** [comment]
@raghavendrarao79 I'm sorry I don't have any real experience with IIB deployed on Bluemix. But from the IIB side if you follow the instructions you posted CORS works. You can try updating to 10.0.0.7, just to be safe Version wise. And then you have to go 'docker exec'  or rsh into the container and investigate from there if your configurations actually are correct.

**Comment by raghavendrarao79** [comment]
Thanks again...we created a new instance of the IBM Integration Bus container instance - 10.0.0.7 - face the same problem after we did similar settings on the IIB container instance as well...Point of confusion for me is whether the "pre-flight" request failure - requires CORS setting at the docker container level OR at the IIB broker side OR both...

Contemplating on this :)...

**Comment by s-rogers** [comment]
This looks like a good conversation, but that there isn't anything required on the repo so cleaning this one up.
