### ISSUE TITLE
Docker exec command does not work as provided

### ISSUE THREAD

**Issue by lopezdsr** [ot4i/iib-docker#26]
This command :-1: Using Docker exec

Use Docker exec to run a non-interactive Bash session that runs any of the Integration Bus commands. For example:

docker exec <container name> /bin/bash -c mqsilist

works if changed to 

docker exec -it <container name> /bin/bash -c mqsilist

**Comment by s-rogers** [comment]
Hi - what version of docker are you using - on my 1.12 setup the first format above works fine for me

Sourcing profile

MQSI 10.0.0.6
/opt/ibm/iib-10.0.0.6/server

BIP1325I: Integration node 'IIBV10NODE' with administration URI 'http://82bcff30f945:4414' is running.
BIP8071I: Successful command completion.
