### ISSUE TITLE
Support for volumes

### ISSUE THREAD

**Issue by geleji** [ot4i/iib-docker#28]
It seems that currently the /var/mqsi structure is created during the Docker build phase, meaning that any volumes attached later at the same point (e.g., when starting the container for the first time) will hide all of the IIB data. It would be nice to have the option of populating /var/mqsi on container start, so that volumes could be handled correctly.

**Comment by geleji** [comment]
#6 seems related

**Comment by dcb-robinson** [comment]
The /var/mqsi structure is indeed created during the docker build phase. If you want to use a volume for the IIB data, then you would need to remove the following line from the Dockerfile:

/opt/ibm/iib-10.0.0.11/iib make registry global accept license silently

and make sure that an equivalent line is added to the iib_manage.sh script. Then you should be able to do the volume that you require.

It is my understanding that we will not be updating the code in master for this use case, so closing this issue.
