### ISSUE TITLE
Docker build failed: /bin/sh ... kernel_settings.sh ... text file busy

### ISSUE THREAD

**Issue by jwende** [ot4i/iib-docker#3]
Build failed - circumvention:
RUN echo "IIB_10:" > /etc/debian_chroot  && \
    touch /var/log/syslog && \
    chown syslog:adm /var/log/syslog && sleep 1 &&\
    chmod +x /tmp/kernel_settings.sh && sleep 1 &&\
    /tmp/kernel_settings.sh

**Comment by s-rogers** [comment]
Hmm - we are not able to recreate this locally - can you provide some more information on the environment you are running in  - e.g. Linux version/level, docker version etc.?

**Comment by jwende** [comment]
Too long ago. Closing ...
J.

**Comment by osamagotji** [comment]
I'm encountering this issue.
How could you solve this problem ?

$ docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
ubuntu              14.04               4a725d3b3b1c        2 weeks ago         188 MB

$ docker info
Containers: 7
 Running: 0
 Paused: 0
 Stopped: 7
Images: 5
Server Version: 1.12.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 22
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host overlay null
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.19-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.92 GiB
Name: moby
ID: ZL7Q:MYL3:TFMF:3MC5:VKEI:7CTF:KJF4:AI56:4377:JVBZ:DWJE:AEZJ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 14
 Goroutines: 23
 System Time: 2016-09-12T22:13:44.6538864Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8

**Comment by osamagotji** [comment]
I just solved the problem.
It's because I use Git on Windows.
And all scripts are cloned using EOL of Windows format.
Just change it to Unix format and everything works fine.

**Comment by mresetar** [comment]
Thanks @osamagotji . Every once in a while this creeps on me. 
I was getting `/bin/sh: 1: /tmp/kernel_settings.sh: not found`. 
In this case gitbash dos2unix tool resolves the problem: 
`dos2unix kernel_settings.sh iib_env.sh iib_manage.sh iib-license-check.sh`
