### ISSUE TITLE
docker build command accepts lowercase only

### ISSUE THREAD

**Issue by petertuton** [ot4i/iib-docker#4]
docker build -t IIBV10IMAGE .
repository name component must match "[a-z0-9]+(?:[._-][a-z0-9]+)*"

docker build -t iibv10image .
Sending build context to Docker daemon 11.26 kB
Step 0 : FROM ubuntu:14.04
14.04: Pulling from library/ubuntu

**Comment by s-rogers** [comment]
This was a change in later versions of docker and used to work - the next commit will use lowercase
