### ISSUE TITLE
exec format error as of 32d2f18

### ISSUE THREAD

**Issue by cullenlinn** [ot4i/iib-docker#44]
Via the latest commit 32d2f18 I receive the following error when attempting to run the container:

standard_init_linux.go:195: exec user process caused "exec format error"

docker version info:
Client:
 Version:       17.12.0-ce
 API version:   1.35
 Go version:    go1.9.2
 Git commit:    c97c6d6
 Built: Wed Dec 27 20:11:19 2017
 OS/Arch:       linux/amd64

Server:
 Engine:
  Version:      17.12.0-ce
  API version:  1.35 (minimum version 1.12)
  Go version:   go1.9.2
  Git commit:   c97c6d6
  Built:        Wed Dec 27 20:09:53 2017
  OS/Arch:      linux/amd64
  Experimental: false

Rebuilt from source using commit 159ce4f and confirmed that it works without issue on the same box / configuration.

**Comment by hobbitcakes** [comment]
Reproduced with kubernetes 1.7.7 on Azure with Docker details below. Rebuilt with 159ce4f and it worked.


Client:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   78d1802
 Built:        Tue Jan 10 20:38:45 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   78d1802
 Built:        Tue Jan 10 20:38:45 2017
 OS/Arch:      linux/amd64

**Comment by andrewyuau** [comment]
Seems to work after running dos2unix on iib_manage.sh.

**Comment by dcb-robinson** [comment]
Some invisible characters (0xEF 0xBB 0xBF) were accidentally added to the beginning of the iib_manage.sh script after an edit was made via a Windows machine. That is why running dos2unix on the script made it work

The actual fix was merged into master in commit 3437bad08e0685ca4ebb71cb72190e62ebc0de24

**Comment by andrewyuau** [comment]
When will the official image "ibmcom/iib-mq-server" be updated?

**Comment by dcb-robinson** [comment]
The official image of "ibmcom/ibm-mq-server" on Docker Hub has now been updated (as of 20 hours ago)
