### ISSUE TITLE
docker pull

### ISSUE THREAD

**Issue by sqlcode1303** [ot4i/iib-docker#45]
I am following docker hub description and usage and ran through following commands but container is not running. 

docker pull ibmcom/iib
and then 
docker run --name myNode -e LICENSE=accept -e NODENAME=MYNODE -e SERVERNAME=MYSERVER -P iib

I am getting below messages but container is not starting up

_Sourcing profile
Set environment variable LICENSE=accept to indicate acceptance of license terms and conditions.

License agreements and information can be viewed by running this image with the environment variable LICENSE=view.  You can also set the LANG environment variable to view the license in a different language._

**Comment by dcb-robinson** [comment]
Hi, apologies for not responding sooner. I notice that you pulled the image down as 'ibmcom/iib' but then tried to run an image called 'iib'.  The fact that something ran suggests that you have an image called iib available in your local docker registry, but that is just a guess.

Can you try to run against ibmcom/iib and let me know how that goes, e.g. 
docker run --name myNode -e LICENSE=accept -e NODENAME=MYNODE -e SERVERNAME=MYSERVER -P ibmcom/iib
