### ISSUE TITLE
standard_init_linux.go:195: exec user process caused "exec format error"

### ISSUE THREAD

**Issue by desmond27** [ot4i/iib-docker#47]
When I attempt to run a `ibmcom/iib-mq-server:latest` image from Docker Hub, I get an error as in the title.

After some research I have learned that such an error could be caused because the shell scripts contain CRLF as line breaks instead of the Unix standard LF. It is likely that the image on Docker Hub is built using the shell scripts with the line breaks as CRLF, causing this issue.

Could someone please verify this and push updated images to the Docker Hub?

**Comment by dcb-robinson** [comment]
Hi, thanks for notifying us about this.

Someone introduced the CRLF line breaks when they made an update to the repo...

I have now pushed a fresh working image onto Docker Hub (tested running on Ubuntu 16.04)

**Comment by desmond27** [comment]
Thanks for the prompt update. I will pull the image and test it in a while.

**Comment by desmond27** [comment]
Yes, the container seems to launch correctly now with the updated image. Thanks for the quick update.
