### ISSUE TITLE
Example run command is missing a space

### ISSUE THREAD

**Issue by petertuton** [ot4i/iib-docker#5]
docker run -e LICENSE=accept -e NODENAME=MYNODE-P IIBV10IMAGE
should be
docker run -e LICENSE=accept -e NODENAME=MYNODE -P IIBV10IMAGE

**Comment by petertuton** [comment]
I suggest also adding a --name param, e.g. --name iibv10 (to avoid a random docker name)

**Comment by s-rogers** [comment]
Agreed - changes made in next commit - thanks!
