### ISSUE TITLE
create broker with -w

### ISSUE THREAD

**Issue by jwende** [ot4i/iib-docker#6]
it's less an issue - more enhancement request:
- expose a volume in the dockerfile:  VOLUME /var/mqsi/data
- change iib_manage.sh: mqsicreatebroker $NODE_NAME -w /var/mqsi/data
  This would give us the option to mount an external volume to store broker runtime data
  Cheers
  Joerg

**Comment by s-rogers** [comment]
Good suggestion - I've been meaning to add in a whole section to the readme on managing state - this seems like a good default setup.

**Comment by s-rogers** [comment]
This requires some though around initialisation of /var/mqsi as expressed in #28  - any updates in this area will be linked to that issue
