### ISSUE TITLE
IIB docker build errors.

### ISSUE THREAD

**Issue by ethiraj** [ot4i/iib-docker#8]
It looks like using current docker file I ran into two issues..

Issue 1 : $ docker build -t iibV10image .
repository name component must match "[a-z0-9]+(?:[._-][a-z0-9]+)*"

I had to update the name  docker build -t iibv10image .

Issue 2 : $ docker build -t iibv10image .
Erro : /bin/sh: 1: /tmp/kernel_settings.sh: Text file busy

I had to update the docker file to include the sync and it works now.

chmod +x /tmp/kernel_settings.sh && \
to 
chmod +x /tmp/kernel_settings.sh;sync && \

**Comment by ethiraj** [comment]
It looks like RobQuads is already working on the fix. Let me know if this is duplicate I can close.

**Comment by s-rogers** [comment]
This should all be fixed now
